### ISSUE TITLE
Example in readme does not work

### ISSUE THREAD

**Issue by pdeblanc** [looking-for-a-job/list-imports.py#1]
Here's my file `file.py`:

```
import math


def foo(x):
    return math.sin(x) + math.cos(x)
```

Here I run the code from `README.md`:

```
Python 3.6.4 (default, Apr 22 2019, 17:19:59)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import list_imports
>>> imports = list_imports.get(open("file.py").read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peter/.pyenv/versions/3.6.4/lib/python3.6/site-packages/list_imports/__init__.py", line 8, in get
    code = open(path).read()
FileNotFoundError: [Errno 2] No such file or directory: 'import math\n\n\ndef foo(x):\n    return math.sin(x) + math.cos(x)\n'
```

**Comment by looking-for-a-job** [comment]
thx. fixed
